# Supabase local development configuration
project_ref = "csbwewirwzeitavhvykr"
project_id = "csbwewirwzeitavhvykr"

[api]
enabled = true
port = 54321

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323